### ISSUE TITLE
backend : Djangoでログイン機能

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#1]
Djangoでどんな感じでログイン機能が作成できるか確認したいです。
https://github.com/Recursion-Group-K/memo/pull/1#discussion_r780646192

**Comment by mcnLeandro** [comment]
Djangoのチュートリアルを通して、Djangoに触ってみました。
tutorial
https://mcnleandro-django-tutorial.herokuapp.com/polls/


記事などみながら、rest_framework(超便利)を使って簡単なAPIを作成しました。
rest_framework
https://mcnleandro-django-second-api.herokuapp.com/api/users/

CORS設定をどこからでもリクエストできるようにしてるので、ターミナルから
```
curl https://mcnleandro-django-second-api.herokuapp.com/api/users/
```

と打つとjsonが取得できます。本番ではCORS設定はフロント(vue)のアドレスのみからにします。


参考記事
https://qiita.com/kimihiro_n/items/86e0a9e619720e57ecd8#djagno-rest-framework%E3%82%92%E7%B5%84%E3%81%BF%E8%BE%BC%E3%82%80

https://qiita.com/frosty/items/66f5dff8fc723387108c#7-2-settingspy

**Comment by mcnLeandro** [comment]
# Python 環境構築

Pythonではnodeのnode_muduleみたいなのはなくて、代わりにvenvを使って「環境を分ける」みたいですね。

使い方はめっちゃ簡単です。
## 自分の場合

例えばDjnagoのプロジェクトを作成するときは普通に作成しちゃいます。

自分はフレームワークや言語単位で、Django用のディレクトリをなぜかCSディレクトリに用意しているので、
```
cd ~/CS/Django
```
場所は任意なので、自分のと当てはめてみてください。

Djangoプロジェクトを作成します。

```
django-admin startproject app_name
```

```
~CS/Django/
  |- app_name/ <= vscodeではこのフォルダを開く
    |- app_name/
    |-manage.py
```

上の通りにvscodeで開く、もしくは移動して
環境フォルダを作成します。
```
~CS/Django/app_name $  python -m venv ./.venv
```

最後の`./.venv` パスと名前です。環境ファイルはどこでも作れますが、vscodeならプロジェクトフォルダ内がいいと思ってます。

```
|- app_name
  |- .venv/
  |- app_name/
  |- manage.py
```
作成した環境に変更します
環境フォルダ内にactivateファイル？があるので実行します。
```
~CS/Django/app_name $ python -m ./.venv/bin/activate
```
これでOK
```
(.venv) ~CS/Django/app_name $
```

環境から戻りたい場合は
```
(.venv) ~CS/Django/app_name $ deactivate
```

また、自分の場合はconda？(まだよくわかっていない)の環境内でこれらの作業をおこなっているので、
こんな感じになってます。
```
(.venv)(base)~CS/Django/app_name $
```

**Comment by tkwonn** [comment]
遅くなりました！すいません！！
rest frameworkまで一通り公式のチュートリアルと載せていただいた記事を参考にしてやってみました。

テスト用のサーバ等も作成していただきありがとうございます。
トークンのことについてはまだ曖昧です。。

https://github.com/jakemcdermott/vue-django-rest-auth

前に@mcnLeandroさんが載せてくれたこちらのリンクですが、認識としてはserverディレクトリにあるようなものを担当するという事で合っていますか？

**Comment by mcnLeandro** [comment]
@tkwonn 
そういう認識であっています！
https://nmomos.com/tips/2019/07/17/django-vuejs-1/
ちなみにこちらも参考になりました。。

あと、UserはカスタムUserを作ってそれを使う形にしたいと思っていたりしています。。。
どんなエンドポイント(url)を用意するのかを表にしたいなと思っていたりしています！

これからサーバーを作成する際に困ったことがあればこちらにissueを立ててくださいね！
https://github.com/Recursion-Group-K/sketch-backend

リポジトリ名が誤字ってたり、コミットが汚かったりしてますが、
テスト用に作った方も興味があればブランチ切って触ってみても問題ないです！(deploy settingしてるので、もしかしたらローカルで動かないかもです。。deploy setting前のコミット探してsettings.pyをコピペしてください)
https://github.com/Recursion-Group-K/cketch-backend-test

**Comment by tkwonn** [comment]
@mcnLeandro 
ありがとうございます！
一旦、テスト用で作成していただいたやつに触れてみます。

終わり次第、issueを立てて随時方向性を確かめていく感じにしたいので宜しくお願いします。

**Comment by mcnLeandro** [comment]
@tkwonn 
いやー自分Djangoもっと早くに触れてけばよかったです笑笑
グダグダになるかもですががんばりましょう！💪

> 終わり次第、issueを立てて随時方向性を確かめていく感じにしたいので宜しくお願いします。
お願いします！👍

**Comment by tkwonn** [comment]
@mcnLeandro 
自分こそレアンドロさんの終えた部分をただ単についていってるだけで申し訳ないです笑

サーバーの構築はやめにしないと進まない所が結構多そうなので急ぎ目で進めていきます！
