### ISSUE TITLE
bug: 認証していれば、作者でなくてもDrawingが編集できてしまう

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#107]

**Comment by sokahiri** [comment]
#110 のaeb6464のコミットで、そもそもログインしている人は自分の作品以外ギャラリーから閲覧できないようにしました。(一瞬読み込まれるがすぐに切り替わる)
ので、認証時は編集できなくなったと思います！
ただ、非同期処理の順番を入れ替えて間違えて表示される確率を下げただけなので、100％阻止できるわけではないと思います。
