### ISSUE TITLE
bug: envの参照

### ISSUE THREAD

**Issue by sokahiri** [Recursion-Group-K/sketch#111]
Twitterのシェアにenvの定数を参照していたのですが、いつの間にかこれが参照できなくなっていました。

**Comment by mcnLeandro** [comment]
僕も伝える際に完全に忘れていたのですが、
VUE_APP_SERVER_URLはAPI側(バックエンド)のurlでした！
新しくVUE_APP_CLIENT_URLという環境変数を.envに追加していました🙏

```
VUE_APP_CLIENT_URL=http://localhost:8080
```

production環境では違うurlになります。でも開発中はこれで問題ないです！
