### ISSUE TITLE
feat/mock/User

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-K/sketch#12]
## 内容
feat/model/Userで作成したモデルのためのモックを作成
後々ユーザーの情報を使うため
- [x] モックを作成する

## その他
 -  [x] ブランチはこのissueと同じブランチ名で作成してください。
  -  [x]  ブランチは用意してあるdevelopブランチから切ってください
  -  [x] プルリクエストはdevelopブランチへ送るようにしてください。
  -  [x]  プルリクエストは完成してなくても進捗シェアのためにできるだけ早めに送るようにしてください。
  -  [x] プルリクエストやコメントをしたらdiscorにもシェアしてくださいね！
  -  [x] レビューをリクエストする前にnpm run lint コマンドを実行してコードを整形してください。コミットも忘れずに。

**Comment by tkwonn** [comment]
モックを作成した経験がないためいくつか質問させてください。

モックについて調べてみると、モック関数によりコード間の繋がりをテストすることができ、関数が持つ実際の実装を除去したり、関数の呼び出しをキャプチャしたり、new によるコンストラクタ関数のインスタンス化をキャプチャできます。 そうすることでテスト時のみの返り値の設定をすることが可能になります。とあります。

https://reffect.co.jp/vue/vue-mock-axios#axiosHTTPMockのリンクを見るとJSONPlaceHolderのユーザ情報を使用していますが、今回のモックもこのAPIデータをテストする形（非同期コードのテスト）という事でしょうか？（１０人のユーザの取得と出力はできています）

リンク先では文字列のチェックを行なったりしていますが、APIから取得したデータは取得できなければ.catchでエラーを吐くかresolveならデータがちゃんと届くことが保証されていると思うのですが、matchers関数では何をテストすればいいのかわからない状態です。

今後ユーザがメールアドレスとパスワードを入れて、例えばメールアドレスなら長さはOO以上であったり、＠が入っていなければならないなどの認証を行うと思うのですが、そういったことをテストするという事をモックを作成してテストするという事でしょうか？

また、ログインする時はそのような入力の検証が必要だと思うのですが、Sign Upの場合、登録済みのユーザ情報の中に該当するものに一致するものがあるのかを調べると思うのですが、これはユーザ情報が格納されているデータベースと通信を行うことで判定するという認識であっていますか？

理解が足りず申し訳ないです。取りかかる前に一応これらの事を聞いておいたほうがいいと思ったので質問させていただきました。
宜しくお願いします。

**Comment by mcnLeandro** [comment]
永続可能なデータが(Django側)がまだ完成していないので、モックを使ってUIを作成するという意味でした。それ自体がテストにあたるものになるかなと思います。自分も詳しくないですが、本格的にやるならjestとか使ってコンポーネントをもっと細分化してテストを書くと思いますが、今回は、いずれAPI通信するので、今API通信しちゃおうということで取得したデータを使って一つのインスタンスとして出力するメソッドを持つクラスを用意しようと思ってました。

確かにモックっていう言い回しはよくないのかもしれないですね。

具体的に例で言うと今はこんなのを作成してもらえれば問題ないです。

```js
class UserWrapper {
    url = "https://json.com"
    constructor(){}
    get(id){
       axios.get(`${this.url}/users/${id}`)
      .then(response => {
        const { id, name, email } = responce.data
         params = {
           id: id,
           name: name,
           email: email
         }
        return new User(params);
      })
    }
    getAll(){
      axios.get(`${this.url}/users`)
      .then(response => {
        return responce.data.map(data => {
          //同じ
        })
      })
    }
}
```

**Comment by mcnLeandro** [comment]
exsampleのtr catchのほうが綺麗になるかもですね。
一番下の例
https://axios-http.com/docs/example

**Comment by Jin2oo2** [comment]
@mcnLeandro 僕もDrawingのモデル作成で同じこと疑問を持っていたのですが上記のコードのDrawingバージョンを作る解釈でいい感じですかね？？
- Drawing(仮名)モデル作成(id, imageUrl, name, userId ....)

- API通信してDrawingモデルを作成して返すラッパークラスを作成する。

-  APIから受け取ったデータを使ってDrawingモデルを作成して返すメソッド作成

API関数の作成とかモック関係今まで触ったことなったので参考になります！

**Comment by mcnLeandro** [comment]
@Jin2oo2 
そうです！それでお願いします！
こんな感じで説明難しい場合があるので、わからない指示があれば聞いてくださいね！

**Comment by tkwonn** [comment]
@mcnLeandro さん、丁寧に説明してくださりありがとうございます！
API通信で取得したデータを使って一つのインスタンスを出力するメソッドを持つラッパークラスの作成って事ですね！

**Comment by tkwonn** [comment]
![Screen Shot 2022-01-12 at 18 20 04](https://user-images.githubusercontent.com/66197642/149254287-bedae1be-6ed5-48ed-b7ce-891930605ff7.png)

mockもmodelsフォルダに置いてしまってよろしいですか？
今はmodels/User.jsにUserモデルを作成し、pages/User.vueにID番号を入れるテキストボックスとSubmitボタンがありテストしていました。
mockは別でブランチを切ってプッシュするため、まずはインスタンスをちゃんと出力できるか確認するためにモックのような役割をUser.vueのメソッドに書きました。

mock（UserWrapperクラス）の置き場所がわかり次第ブランチを切ってそこに配置しようと思っています。
こんな感じでよろしいか一度ご確認いただければと思います！

**Comment by tkwonn** [comment]
models/User.js

export class User {
  constructor(params){
    this.id = params.id;
    this.name = params.name;
    this.email = params.email;
    this.password = params.password;
  }
}


pages/User.vue

methods: {
      getUserWithId: function(){
        this.axios
        .get(`https://jsonplaceholder.typicode.com/users/${this.id}`)
        .then(response => {
          const params = {id: response.data.id, name: response.data.name, email: response.data.email, password: response.data.username}
          this.user = new User(params)
        })
        .catch(error => {
          console.log(error)
          this.errored = true
        })
        .finally(() => this.loading = false)
      } 
    }

みたいな感じです！

**Comment by tkwonn** [comment]
urlもgetの中に直で書くのではなく、UserWrapperクラス内に記入する予定です

**Comment by mcnLeandro** [comment]
@tkwonn 
UserWrapperクラスはapi通信するのでapiフォルダに入れようと思っていました！
https://github.com/Recursion-Group-K/memo/blob/main/FileTree.md

あと、インスタンスの出力はnode.jsを使うと便利です！
今決めたんですが、testフォルダを作成してください↑↑
userWrapperTest.jsファイルを作成して、
中身は 簡単にこんな感じにしてください。
```js
import UserWrapper from '../api/UserWrapper'

const user1 = await new UserWrapper().get(1)

console.log(user1)
```

```
node test/userWrapperTest.js
```

これで実行してコンソールから確認できるか試していただきたいです！

**Comment by tkwonn** [comment]
ありがとうございます！承知しました！

**Comment by tkwonn** [comment]
![Screen Shot 2022-01-13 at 0 56 25](https://user-images.githubusercontent.com/66197642/149298004-a0d59248-46bb-4840-9f4a-86de73e27ace.png)

テストを実行してコンソールでは確認できたんですが、npm run serveで以下のようなエラーが出てしまいます。
![Screen Shot 2022-01-13 at 0 57 30](https://user-images.githubusercontent.com/66197642/149298143-5cf13183-c407-47c5-9835-a8175f3626f6.png)

思い当たる部分：
node.jsでテストを行う際にimport UserWrapper from '../api/userWrapper.jsのようにインポートする場合、package.jsonにてtype:"module"と記載する必要があるとのエラーがでてきました。

エラー文：
(node:72113) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

なのでそのように変更した所、上記のようなエラーがでました。

やったみた事：

https://stackoverflow.com/questions/61146112/error-while-loading-config-you-appear-to-be-using-a-native-ecmascript-module-cのサイトであるようにbable.config.jsを変更してみましたがそれでも同じようなエラーがでてきます。

babelの公式も見てみましたが理解できなかったのでこのような場合の解決法がありましたらアドバイスお願いします。。

**Comment by tkwonn** [comment]
一度途中経過としてプルリクエストを出してコードを実際にみたほうがよろしければそのように致します！

**Comment by mcnLeandro** [comment]
そうですね！一旦プルリクエストお願いします！
プルリクする時に右のサイドバーの中にissueを設定できる場所があるので、このissueを設定しておいてもらえると助かります！

![sshot 27](https://user-images.githubusercontent.com/72016706/149303382-83dc7981-6fab-4649-ae25-f5886ee075b1.png)

あと、コメントでもハッシュタグと数字でissueやプルリクエストのリンクを作成できるので使ってみてください！
例: #12

**Comment by tkwonn** [comment]
テスト通過、npm run lint問題なしでプッシュしておきました！
npm run lintでエラーがでなかった部分に関しては#15を参照ください。
確認お願いします１
