### ISSUE TITLE
bug: npm run lint エラー

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-K/sketch#15]
## 内容：

- vue add unit-jestを行ってからnpm run lintでエラーが出るようになった。

## エラー文

error: Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?

## エラーが発生している所

- feat/model/User

ちなみにfeat/mock/Userではnpm run lintエラーはなかったです。おそらく.eslintr.js, babel.configのファイルに違いがあることからそれらが原因だと思います。

![Screen Shot 2022-01-14 at 17 25 19](https://user-images.githubusercontent.com/66197642/149604156-10fc913c-70f3-4e08-acc9-534f235e2eb2.png)

それぞれのコードを貼っておきます。

feat/model/User:
https://github.com/Recursion-Group-K/sketch/pull/13/files

feat/mock/User:
https://github.com/Recursion-Group-K/sketch/pull/14/files

**Comment by mcnLeandro** [comment]
jest 入れた時点で　.eslintrc.js に変更があったのに気づきました。

変更前
```js
module.exports = {
    root: true,
    env: {
        node: true,
    },
    extends: ['plugin:vue/essential', 'eslint:recommended', '@vue/prettier'],
    parserOptions: {
        parser: 'babel-eslint',
    },
    rules: {
        'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    },
};
```

変更後
```js

module.exports = {
    parser: 'babel-eslint',
    overrides: [
        {
        files: [
            '**/__tests__/*.{j,t}s?(x)',
            '**/tests/unit/**/*.spec.{j,t}s?(x)'
        ],
        env: {
            jest: true
        }
        }
    ]
}
```


以下のように編集してみてください。
```
module.exports = {
    root: true,
    env: {
        node: true,
    },
    extends: ['plugin:vue/essential', 'eslint:recommended', '@vue/prettier'],
    parserOptions: {
        parser: 'babel-eslint',
    },
    rules: {
        'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    },
    overrides: [
        {
        files: [
            '**/__tests__/*.{j,t}s?(x)',
            '**/tests/unit/**/*.spec.{j,t}s?(x)'
        ],
        env: {
            jest: true
        }
        }
    ]
};
```

これでどうなりますか？？

**Comment by mcnLeandro** [comment]
https://github.com/Recursion-Group-K/sketch/pull/14/files
でも、こっちのプルリクではうまく編集できてるみたいです。

feat/mock/userブランチで試すとどうなりますか？？

**Comment by mcnLeandro** [comment]
自分の環境ではうまくいきました！

**Comment by mcnLeandro** [comment]
vue add コマンドで、このファイルを上書きしてしまっていたみたいですね。

**Comment by tkwonn** [comment]
おかげさまでfeat/mock/User, feat/model/User共に正常に処理が行われました！

**Comment by mcnLeandro** [comment]
よかったです！
