### ISSUE TITLE
Research: vue-Konvaの Save/Loadについて

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#2]
https://konvajs.org/docs/vue/Save-Load.html#page-title
ここで書かれている注意

 > 注意: But we don’t recommend to use these methods if you are using vue-konva. In vue-konva you should have a state of the app defined in your vue components. That state maps into nodes with templates. To save/load full stage you just need to save/load state of the app and you don’t need to save Konva internals and nodes.
 
 vue-Konvaを使う場合は注意が必要とのこと, リンク先のコメントで話してる内容を見る限り、Konvaが提供してるメソッドでJSONを読み込むんじゃなくて、VueのState(dataとか？)を丸ごとjson化してparseするってこと？やってみないとわからない部分があるので、調査が必要かも。。。ということで調査します。。。

**Comment by mcnLeandro** [comment]
https://codesandbox.io/s/github/konvajs/site/tree/master/vue-demos/save-load?from-embed=&file=/src/App.vue:957-1154

**Comment by mcnLeandro** [comment]
なるほど。vue-konvaではdataの中身ははstageではなく「circleやrectを表示するためのConfig」なので、これをJSON化するには単純にこれを

**Comment by mcnLeandro** [comment]
- Konva.Node.create
- Konva.Node.toJson

これらは使うまでもなかった。
解決だと思います！

**Comment by tkwonn** [comment]
ありがとうございます！
普通のKonvaではインスタンスを生成して.addメソッドでStageやらLayerやらに追加する所をVueではDataにConfigを渡してあげればいいという事ですね！

**Comment by mcnLeandro** [comment]
そういうことです！！
