### ISSUE TITLE
Favicon＆Logo

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#3]
- [x] ロゴを作成して欲しいです！

これはアイデアをいくつか用意してみんなにどれがいいか聞く形式で、場合によってはアイデアを混ぜたりしながら決めましょう！
デザインが苦手な場合は、
https://www.tailorbrands.com/lp-home?utm_source=google&utm_medium=cpc&utm_campaign=774397903&utm_content=41015689352&utm_term=logo%20generator&gclid=Cj0KCQiAieWOBhCYARIsANcOw0xKB-yJQadcSp197RmV83jILGEtLDiZnGvTHxGSNZS6ABFVyojRZvwaArogEALw_wcB

Logo generator で検索したらいろんなサイトがマッチするはずです！

- [x] ファビコンを作成したいです！

画像の作成の方法はなんでもいいですが！

一旦表示させてみてうまくいったらプルリク送ってください。
画像付きでお願いします！

あと余裕があれば
どのデバイスが表示にも対応できるようにいくつかの画像ファイルが用意できればまるです！

https://favicon.io/favicon-converter/
https://ao-system.net/favicongenerator/
https://realfavicongenerator.net/

前回こんなのも使ってみました画像を作成するやつですね。アニメーションはうまくいかなかったんですが、面白いサービスです
https://www.favicon.cc/

**Comment by tkwonn** [comment]
![logo](https://user-images.githubusercontent.com/66197642/148736948-5bdb7795-baf6-4650-9efb-61a640e9f4d7.jpg)

**Comment by tkwonn** [comment]
![logo](https://user-images.githubusercontent.com/66197642/148736969-276de472-0fed-4058-b244-b24ce9050902.jpg)

無料でロゴを作成できると謳って実は有料なサイトに何回かやられましたがこちらのサイトhttps://www.designevo.com/ではTwitterでシェアしたら無料でダウンロードできました。
デザインはもう少し粘ってみますが何かご意見ありますか？

**Comment by tkwonn** [comment]
候補２
![logo](https://user-images.githubusercontent.com/66197642/148737374-480b42fc-67ff-4e1e-8b5d-4b78b0fe81c4.jpg)

**Comment by tkwonn** [comment]
候補３
![logo](https://user-images.githubusercontent.com/66197642/148737718-794366d6-0e05-4b0c-854a-e31d3929061d.jpg)

**Comment by tkwonn** [comment]
faviconはロゴと統一性を持たせたほうがいいかと思ったのでまずロゴだけしておきました。

**Comment by mcnLeandro** [comment]
@tkwonn 
kwonさんに的にはどれが好みですか？？

@Jin2oo2  @sokahiri  お二人もどれが好みですか？？

**Comment by sokahiri** [comment]
作成ありがとうございます！めっちゃすごいです！！
自分は候補1が1番好きです！

**Comment by tkwonn** [comment]
僕も1番目がシンプルでいいかなと思いました。
もう少し候補を出してみることもできますがどうしますか？

**Comment by Jin2oo2** [comment]
多数決で1でいいかなと思います！

**Comment by tkwonn** [comment]
了解で
![icon-160x160](https://user-images.githubusercontent.com/66197642/148842487-1764d0d4-4840-4548-bf77-1ce2c72e5a55.png)
す！
faviconは1番目のロゴをそのままfavicon generatorで生成したやつはどうですか？

**Comment by Jin2oo2** [comment]
いいですね！
それでいきましょう。

**Comment by mcnLeandro** [comment]
決まりですね！

**Comment by tkwonn** [comment]
![Screen Shot 2022-01-11 at 16 41 40](https://user-images.githubusercontent.com/66197642/149043589-dd134687-77d1-4c52-8583-582aac174c45.png)
少し画質荒いですが、小さくてあまり見えないのでこれでよろしいですか？

**Comment by mcnLeandro** [comment]
@tkwonn 
そうですね！確かにちょっとみにくいので
文字を消したキャンパス？だけの画像をスクショか何かで用意してもらえればと思います！

![sshot 26](https://user-images.githubusercontent.com/72016706/149053167-02f90f67-39ba-485a-afa4-d14cca906a31.png)

**Comment by tkwonn** [comment]
了解です！

**Comment by tkwonn** [comment]
![Screen Shot 2022-01-11 at 18 43 17](https://user-images.githubusercontent.com/66197642/149054417-147e44cd-523f-4761-9bcf-965a07ad78e1.png)
これでどうでしょうか？

**Comment by mcnLeandro** [comment]
自分はいい感じだと思います！！

@Jin2oo2 @sokahiri

**Comment by mcnLeandro** [comment]
クローズします！
