### ISSUE TITLE
WireFrame

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#4]
https://whimsical.com/wireframe-sketch-app-GbLY9SJKSKubmX7JtpaJd2

ワイヤフレームを決定、or 変更します。

変更したい部分があればコメントしてください！
このままでいい場合もコメントしてください！

全員がいいと思ったら実際にページの作成に取り掛かります（HTML のみ）

**Comment by Jin2oo2** [comment]
僕はこれでいいと思います！

**Comment by sokahiri** [comment]
Drowingページについて、スマホでの動作を想定するなら機能ボタンは上部か下部に配置したほうがいいと思いました。
左右に描画用の入力を配置するので、上部か下部の方が邪魔にならなさそうです。
他のページにつきましては自分もこれでいいと思います！

**Comment by mcnLeandro** [comment]
描画スペースを確保するという意味では、
whimsicalみたいなサイドバーにしちゃえば解決するかもですね。whimsicalは左上のボタンを押すとファイルツリーが消えます

どちらにせよそのページを変更する必要がありそうです！
どなたかお願いできますか？

@sokahiri  @tkwonn @Jin2oo2

**Comment by tkwonn** [comment]
Whimsicalのサイドバーを意識して変更してみましたがこんな感じでしょうか？
https://whimsical.com/wireframe-sketch-app-GbLY9SJKSKubmX7JtpaJd2

**Comment by sokahiri** [comment]
スマホブラウザ向けのワイヤフレームだと思っていましたが、改めてよく見てみるとPCブラウザでのワイヤフレームを決めていたんですね。スマホブラウザ向けに作るなら、描画の操作性のために左右の対称性が重要だと考えていますが、PCブラウザでしたら特に気にしなくていい要素かもしれませんね...主張が二転三転してしまっていて申し訳ありません。
一応WhimsicalのDrawingページ案の最後に自分の案も載せておきました！こんな感じで作ったらスマホ版とPC版でデザインを大きく変える必要もないのかなと思います。

**Comment by mcnLeandro** [comment]
@tkwonn 
ファイルツリーは今回は必要ないかと思ったので、ファイルツリーの代わりにペンや色などのオプションが出てくるように変更しました！

ファイルツリーを作ってはいけないわけではないのでもし作成したい場合は相談しましょう！！
vueで作ったら結構簡単に作れるはずです（？）

**Comment by mcnLeandro** [comment]
@sokahiri 

いいと思います！
ヘッダーは文字よりもアイコンの方が直感的ですね！

**Comment by tkwonn** [comment]
@sokahiri さんのDrawingページ案すごく良いと思います！！

**Comment by Jin2oo2** [comment]
@sokahiri さんの案で賛成です！

**Comment by mcnLeandro** [comment]
OKです！

そしたらHTMLを作り始めるために新たにissueを作成するので少々お待ちください！
