### ISSUE TITLE
feat/models/User/update

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#43]
https://sketch-skgl-server-test.herokuapp.com/

こちらのサーバーっで急遽用意したモデルがUserとDrawingです。それぞれ以下のカラムを提供します。
このissueではフロント側のUserWrapperクラスを正しく修正してください！

```
User
- id 
- username
- password ×
- is_superuser ×
- is_active
```
×と書いてあるカラムはフロント側のUserモデルでは必要ない情報なので受け取らないように注意してください。

さらに
DMで教えたスーパーユーザーの情報とバックエンドのurlの三つを.envファイルに記述してください
```.env
SUPERUSER_NAME =
SUPERUSER_PASSWORD =
SERVER_URL =
```
https://www.npmjs.com/package/dotenv
.envファイルを作成し。.gitignoreファイルに追記してください。

また、DjangoのデフォルトのUserモデルをなんとか使っているのでカスタムUserに変更する予定なので、さらに変更が発生するかもしれませんが、先に認証機能を完成させるためにこちらの修正をお願いします！

**Comment by Jin2oo2** [comment]
@mcnLeandro サーバーURLはhttps://sketch-skgl-server-test.herokuapp.com/ ですか？

**Comment by mcnLeandro** [comment]
@Jin2oo2 
そうです！
