### ISSUE TITLE
feat/Auth/Login

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#44]
- [x] #43 
- [ ] フロントで認証機能(ログイン)を完成させてください。

まず自分でどんな時に、どんなレスポンスが帰ってくるかを確かめてから取り組むといいです！

curlを使うことができますが、httpieの方が簡単なので、こっちを使います。
https://httpie.io/docs/cli/pypi
```
brew update
brew install httpie
```

あらかじめユーザーを作成しておきました。
```
username=test2
password=test2
```

以下のurlは認証をしてTokenを返すエンドポイントです。
```
https://sketch-skgl-server-test.herokuapp.com/auth/ 
```

以下のようにusernameとpasswordで認証できます。認証がうまくいった場合はTokenが帰ってくるのでフロント側ではそれを受け取ります。もちろんjs内ではaxiosを使います。ちなみにこれはPOSTリクエストです。

```
 http https://sketch-skgl-server-test.herokuapp.com/auth/ username="test2" password="test2"
```

js内でtokeが受け取れたらそのTokenをCookieに保存します。
https://www.npmjs.com/package/js-cookie

Cookieに保存する際はDjangoの仕様なのですが、以下のように保存してください。
Tokenの文字の後に半角が必要なので注意
```
Cookie.set("Token " + token)
```

これで実質ログインは完了です。

さらに追加で、SignUpページ,Loginページ,Homeページなどで、Cookie内を調べてtokenがあればtokenを元にuserを特定してガラリーページまで遷移っていうところまでいきたいですが、別のissueにしますね。

困ったらいってください。

**Comment by Jin2oo2** [comment]
@mcnLeandro 今js内でaxiosでtokenを取得しようとしているところで2つ質問があります。

> 以下のようにusernameとpasswordで認証できます。認証がうまくいった場合はTokenが帰ってくるのでフロント側ではそれを受け取ります。もちろんjs内ではaxiosを使います。ちなみにこれはPOSTリクエストです。
 http https://sketch-skgl-server-test.herokuapp.com/auth/ username="test2" password="test2"

こちらはbasic認証でしょうか？その場合は #43 と同じ感じでaxios.postの第三引数にauthプロパティを加えればいいだけだと思ったのですがうまくいかないので。

それとjsでtokenを受け取るファイルはapiフォルダにtokenAuth.jsみたいな感じでやればいいですか？

**Comment by mcnLeandro** [comment]
それは確かPOSTでbodyとしてログイン情報を送る形だと思います！
なのでauthではなく第2引数に{username: ... ,password:....}を入れてあげるとPOSTできたはずです！
https://qiita.com/chenglin/items/f59a6daff76fa0f582af#post%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89

**Comment by Jin2oo2** [comment]
@mcnLeandro ありがとうございますtoken取得できました！
