### ISSUE TITLE
fix/pages/Drawing/layout

### ISSUE THREAD

**Issue by sokahiri** [Recursion-Group-K/sketch#47]
#17 で挙がっていました、余裕があれば実装したい機能です。
- [x] サイドバー展開
- [ ] タッチデバイスの縦/横置きの認識とそれに応じたレイアウトの作成。
- [x] 現在ボタンを出すかどうかを画面サイズで決めてしまっていますが、タッチデバイスかどうかを認識してボタンを出すような仕様にするべきかなと考えています。
- [ ] タッチデバイスの時ダブルタップやスクロールを禁止にする機能の実装。

**Comment by mcnLeandro** [comment]
すみません。完全に忘れていました。。。
こちらは僕が一旦進めておきます！

**Comment by mcnLeandro** [comment]
- [ ] #48 
- [ ]
