### ISSUE TITLE
feat/pages/Gallery

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#5]
## 内容 
[Wireframe]( https://whimsical.com/wireframe-Fgq6U4HcxRb5aBWLjbFdzv)
- [ ] Galleryページを作成してください！

## モック

必要に応じてモックを使ってください。
今のうちにAPI通信にも慣れておきましょう。(ブーメラン笑)
https://jsonplaceholder.typicode.com/
例 [phtos]:https://jsonplaceholder.typicode.com/albums/1/photos)

参考
axsios: https://jp.vuejs.org/v2/cookbook/using-axios-to-consume-apis.html
mock: https://reffect.co.jp/vue/vue-mock-axios#axiosHTTPMock

## ファイル

ファイルの置き場所はこちらを参考にしてください。
FileTree.md: https://github.com/Recursion-Group-K/memo/blob/main/FileTree.md

それでもわからない場合は質問してください！

## 手順
- [x] Drawing(仮名)モデル作成(id, imageUrl, name, userId ....)
- [x] API通信してDrawingモデルを作成して返すラッパークラスを作成する。
- [x] APIから受け取ったデータを使ってDrawingモデルを作成して返すメソッド作成
- [ ] Gelleryページを作成する
- [x] route設定
...
- 実際のデータが使用可能になったらラッパークラスを変更する

## その他

- [x] ブランチはこのissueと同じブランチ名で作成してください。
- [x] ブランチは用意してあるdevelopブランチから切ってください
- [x] プルリクエストはdevelopブランチへ送るようにしてください。
- [x] プルリクエストは完成してなくても進捗シェアのためにできるだけ早めに送るようにしてください。
- [ ] プルリクエストやコメントをしたらdiscorにもシェアしてくださいね！
- [ ] レビューをリクエストする前に`npm run lint` コマンドを実行してコードを整形してください。コミットも忘れずに。
 
## 最後に

ちょっと大量ですが、お願いします！
ページを完成させるために、いくつかさらにissueを分けてもらっても構いません。その際のissueの作成はこのissueのリンクと、その他の項目を継承して書くようにしてください。

個人的な意見ですが、

- Modelだけ作るissue
- HTMLだけ作るissue
- 最後にこのissueみたいに進めるとスムーズなんじゃないでしょうか

もちろん複数人でやっても構いません。その場合は、できるだけコミュニケーションを積極的に取るようにお願いします！
チーム開発では大袈裟なコミュニケーションくらいがちょうどいいです。(このチームは時差があるのでしょうがない部分もあります)

**Comment by Jin2oo2** [comment]
Drawingモデルで持つべデータについて質問があります。最終的には必要なデータが増えたり減ったりしてその都度変更を加えればいいと思うのですが、とりあえずみなさんにどのようなデータが必要そうか意見を出していただきたいです！
`
export class Drawing {
    constructor(params) {
        this.id = params.id
        this.imgUrl = params.imgUrl
        this.title = params.title
        this.userId = this.userId
    }
}
`
現状はこんな感じですが作成した日時(date)をもったりもあるかなと思います。

**Comment by mcnLeandro** [comment]
@Jin2oo2 
そんなのがあるんですね！
使ってもらっても問題ないです！

**Comment by tkwonn** [comment]
必要なデータは上記の7つでいいと思います！
