### ISSUE TITLE
confirm: DrawingFormについて

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#50]
> こちらのDrawingFormはどういった機能なんでしょうか？

これはDrawingの新規作成のためのフォームですね！他の場所の方がいいと思いますか？？

_Originally posted by @mcnLeandro in https://github.com/Recursion-Group-K/sketch/issues/19#issuecomment-1021953722_

**Comment by tkwonn** [comment]
場所はそのままでいいと思います！

![Screen Shot 2022-01-26 at 5 31 56](https://user-images.githubusercontent.com/66197642/151172272-230592c0-53d4-4af7-93aa-c132680e3313.png)

ただ個人的にはこのようなデザインだとわかりやすいかなと思いました。

**Comment by mcnLeandro** [comment]
やってみますね！

**Comment by tkwonn** [comment]
ありがとうございます！
