### ISSUE TITLE
confirm: Drawingモードとページ

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#51]
@sokahiri 
ありがとうございます！
> 今のところはDrawing/etchASketchと、Drawing/normal(できるなら)のような2種類のDrawingページを用意して、modeの変更に応じてページを変更するような仕様にしようかなと思いました

自分もそう思います！二つのモードの処理を同じページ(コンポーネント)に書くのは可読性が低くなりますし、分解するべきですね！

_Originally posted by @mcnLeandro in https://github.com/Recursion-Group-K/sketch/issues/39#issuecomment-1021942015_

**Comment by mcnLeandro** [comment]
これに関して思ったことはページを分けることには賛成ということと、
DrawingモデルにもそのDrawingはそういうモードで書かれたのかという情報を持っておく執拗があるのかなと思いました。

modeカラムを追加することで、GalleryページのDrawingの見た目を変えたりクリックした際の遷移先を変更する際に使えます。

**Comment by sokahiri** [comment]
確かにその通りですね。自分もdrawingモデルにモードを保管しておく必要があると思います。
modelにモードを管理するパラメータを追加することのほかに必要な実装はありますか？
思いついたこととして、DrawingToolページに現在何モードの描画なのかが示されていれば分かりやすそうですが、これは必須ではないですね。

**Comment by mcnLeandro** [comment]
https://github.com/Recursion-Group-K/sketch/pull/39#issuecomment-1022220829

@tkwonn 
全くその通りですね笑
今回は、バックエンド側のDrawingモデルにはmodeカラムを持たせる方向で行きます。
あとは時間が余った時にフロント側のWrapperクラスからそれを受け取るだけで問題ないです。

**Comment by mcnLeandro** [comment]
https://github.com/Recursion-Group-K/sketch-backend/issues/4
