### ISSUE TITLE
confirm: レスポンシブについて

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#56]
自分のスマホで見た時にレスポンシブ対応をするのは時間がかかりそうかなと感じたので、デスクトップを優先すべきと感じました。

https://github.com/Recursion-Group-K/sketch/pull/54#issue-1116401242
#47

**Comment by sokahiri** [comment]
賛成です！
スマホでのテストは現在行えますか？

**Comment by mcnLeandro** [comment]
![sshot](https://user-images.githubusercontent.com/72016706/151486881-b5b99c04-a6df-40fd-a8b3-4cdf61be2cd1.png)

自宅のwifiを使って一時的にwifi内での共有IPアドレスができるみたいです。netwotlの方のやつですね。
これにスマホからアクセスすれば(safariやchormeで)みれます！

**Comment by tkwonn** [comment]
自分も賛成です！
