### ISSUE TITLE
Confirm: redo undoの場所

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#59]
![sshot 39](https://user-images.githubusercontent.com/72016706/151415408-5efb0ed7-f605-49ba-a14c-efc4ddd1cc51.png)

https://github.com/Recursion-Group-K/sketch/pull/57#pullrequestreview-865233260

reso undoはツールバー以外の場所にあった方がいいのかなと思ったりしています。
みなさんどう思いますか？？

あと、それぞれボタンを押しすぎて文字を選択してしまったりするので、これも治しておきたいです。
- 場所を移動するか
- user-pointer noneにするか
![sshot](https://user-images.githubusercontent.com/72016706/151415741-a5a1ce2a-4222-4594-929a-cfb094c32f3f.png)

**Comment by sokahiri** [comment]
確かに線の修正は色や太さ変更よりも気軽に行いたいですね。redo/undoをツールバー以外の別の場所に置くのは賛成です！
colorボタンについてはホバーで暗くなる部分のどこをクリックしてもピッカーが出るようになるともっと直感的かもしれないですね。自分は透明なカラーインプットを最前面に配置することで似たような内容の実装をしていました！
文字選択について、レイアウトはこれでいいと思うので、ポインターできなくするのがいいと思いました。

**Comment by tkwonn** [comment]
自分も文字選択はuser-pointer noneに賛成です。この前、フェッチして少しみた感じだとredo/undoはCanvasを少しだけ小さくし空いたスペースのどこかに入れるか、左右に配置されているボタンの間ですかね？
