### ISSUE TITLE
feat/pages/Drawing

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#6]
## 内容 
[Wireframe]( https://whimsical.com/wireframe-Fgq6U4HcxRb5aBWLjbFdzv)
- [ ] Drawingページを作成してください！

## モック

Drawingページではモックはまだ必要ないかなと思いますが、必要に応じてモックを使ってください。
Galleryのissueを参考にしてください。

https://github.com/Recursion-Group-K/sketch/issues/5

## ファイル

ファイルの置き場所はこちらを参考にしてください。
FileTree.md: https://github.com/Recursion-Group-K/memo/blob/main/FileTree.md

それでもわからない場合は質問してください！

## 手順

- [ ]  Drawingページを作成する
- [ ] route設定をする

## その他

- [ ] ブランチはこのissueと同じブランチ名で作成してください。
- [ ] ブランチは用意してあるdevelopブランチから切ってください
- [ ] プルリクエストはdevelopブランチへ送るようにしてください。
- [ ] プルリクエストは完成してなくても進捗シェアのためにできるだけ早めに送るようにしてください。
- [ ] プルリクエストやコメントをしたらdiscorにもシェアしてくださいね！
- [ ] レビューをリクエストする前に`npm run lint` コマンドを実行してコードを整形してください。コミットも忘れずに。
 
## 最後に

このissueはレイアウト作成との戦いになりそうですね！
導入している Bluma CSSなどを駆使して作成をお願いします！

**Comment by sokahiri** [comment]
@mcnLeandro 
大変初歩的な質問で恐縮です。
ファイル階層についてですが、FileTree.mdのようにsrc直下にcomponentsが見当たりません。現在Developからブランチを切ってnpm installした状態です。
ヘッダー等は部品に分けて書こうと考えているのですが、必要になったらcomponentsフォルダを自分で作ってしまってよいのでしょうか？

**Comment by mcnLeandro** [comment]
@sokahiri 
はい！
同じ名前であれば作成していただいて問題ないです！
