### ISSUE TITLE
confirm:PCで描画の幅を増やすための案

### ISSUE THREAD

**Issue by sokahiri** [Recursion-Group-K/sketch#60]
今のところ、上下左右に1つずつキーを割り当てて絵を書く仕様ですが、1つの方向につき複数(2~4)のキーを割り当てて、キーを押した量だけ移動量が増える仕様にすればもっと柔軟な描画が可能になると思いました。
皆さんはこの仕様をどう思いますか？意見をお願いします。

**Comment by mcnLeandro** [comment]
キーを押し続ければ押し続けるほど移動が速くなるということですか？

正直、実際に動かしてみないとわからないですね。。
時間が余ったら作ってみてもいいかもしれないです！確かに、今の描画はカクカクなのでそれが修正できるなら取り入れたいですね！

**Comment by tkwonn** [comment]
確かにそれはありだと思います！余裕があればお願いしたいですね。
上下左右がwasdであればそれぞれに同じ複数のキーを割り当てたいですね。

**Comment by sokahiri** [comment]
ありがとうございます！
では、余裕があれば実装してみます！
