### ISSUE TITLE
confirm: reso&undoの仕様

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#61]
コンフリクトの解消行いました。
あと、現在戻るをしたときに戻るのはポインター位置だけで太さや色は戻らないようになっていますが、太さや色も戻る仕様にした方がいいですか？
ちなみに自分は別にここは変えなくてもいいと思っています。使い方にもよると思いますが、自分は線の修正をしたいときに色や太さまで戻られるとむしろ困るような気がするので。

_Originally posted by @sokahiri in https://github.com/Recursion-Group-K/sketch/pull/53#issuecomment-1023528509_

**Comment by mcnLeandro** [comment]
自分もなくていいと思います！

**Comment by tkwonn** [comment]
自分もなくていい派ですね！

**Comment by mcnLeandro** [comment]
クローズします！
