### ISSUE TITLE
feat/SIgnUp

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#85]
サインアップ機能を作成してください。
https://github.dev/jakemcdermott/vue-django-rest-auth
こちら参考にしたり、マージしてあるログイン機能を参考にしてください！

**Comment by tkwonn** [comment]
## 保留
Loginに失敗したあと、SignUpページに移行するとLoginページでのエラー文がSignUpページにも表示されてしまう。

**Comment by tkwonn** [comment]
@mcnLeandro 

了解です！

**Comment by tkwonn** [comment]
>Loginに失敗したあと、SignUpページに移行するとLoginページでのエラー文がSignUpページにも表示されてしまう。

こちら今気づいたんですが、最適な解決策はわかりませんがSignUp時にはisisAuthenticatedFailedは確認しなくてもOkかと思いますので、そのまま外しておくことにしました。
